name: Release docker image (jito)
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+\-jito'

jobs:
  docker:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Jito-solana repo
        uses: actions/checkout@v3
        with:
          repository: jito-foundation/jito-solana
          ref: ${{ github.ref_name }}
          submodules: 'recursive'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Jito-solana
        run: |
          set -x
          CI="" ./sdk/docker-solana/build.sh
          docker tag solanalabs/solana:${{ github.ref_name }} docker-solana:${{ github.ref_name }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=raw,value=latest-jito
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.jito
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.event.repository.name }} ${{ github.ref_name }}
          makeLatest: false
          generateReleaseNotes: true
          body: |
            ## Docker images
            ```
            ${{ steps.meta.outputs.tags }}
            ```